### PR TITLE
Enhance WHMCS plugin/module

### PR DESCRIPTION
**Pull request by Andrenzo17**
- add system module log
- improve button ui
- update notif handler
- update installation on whmcs 8.3

### CODE REVIEW

**Comment by Xaxxis** [comment]
@Andrenzo17 also please add how to enable log on the readme, like our [others plugins](https://github.com/Midtrans/Midtrans-Magento2#log-options) ya

**Comment by Andrenzo17** [comment]
Thanks for feedback @Xaxxis 🙏

**Comment by rizdaprasetya** [comment]
@Andrenzo17  on the new log section on readme, can you specify how merchant can access/view the log?

**Comment by Andrenzo17** [comment]
In the same page when they enable module logging kak.
Go to `Configuration > System Logs > Module Log (Utilities > Logs > Module Log in WHMCS 7.x and earlier)`.

**Comment by Andrenzo17** [comment]
image

**Comment by rizdaprasetya** [comment]
@Andrenzo17 🤦 I was asking you **to write it on the readme**, if the log is visible on that page, than **explicitly** write that on the readme. So that user can understand.

Also what does this sentence even means:
> If you are experiencing a technical issue with a module, enable logging:

Are you hinting that enabling logging will solve the "technical issue"? Improve the wording for example to:
> Enabling logging can help you trace what happened and help troubleshoot technical issues.

**Comment by Andrenzo17** [comment]
Sorry for my wrong assumption, i have write on the readme how to access/view log.
Thank you

**Review by rizdaprasetya — COMMENTED** [review]
Actually the enhancement was a little less than what I expected, but for now let's close it because it was open for too long. This module still need some further enhancement, but will assign as later task.

Also same note on commit message, your commit message was poor e.g `update notif handler` was not helpful in explaining the changes. Here's some [real example](https://github.com/veritrans/SNAP-Woocommerce/commits/71852ecdff48b5cfe2d098c22536611be5c34fb2/class/class.midtrans-gateway-notif-handler.php) of more descriptive commit messages.

I'll merge now, please announce on reelase channel. Thanks

**Pull request merged**
